import uniqid from "uniqid";
import Head from "next/head";
import { useState, useEffect } from "react";
import { initializeApp } from "firebase/app";
import { getDatabase, ref, set, onValue } from "firebase/database";

import 'bootstrap/dist/css/bootstrap.min.css';

import styles from "../styles/Home.module.css";
import Temperature from "../src/components/Temperature";
import { Col, Container, Row } from "react-bootstrap";
import Birds from "../src/components/Birds";
import FoodWater from "../src/components/FoodWater";

const firebaseConfig = {
  apiKey: "AIzaSyCS2xpG7sXRq6QzVzPT_uj3CRwj8b-N-JU",
  authDomain: "aviaryiot-se.firebaseapp.com",
  databaseURL: "https://aviaryiot-se-default-rtdb.firebaseio.com",
  projectId: "aviaryiot-se",
  storageBucket: "aviaryiot-se.appspot.com",
  messagingSenderId: "73299433036",
  appId: "1:73299433036:web:6dafb44d4597408822c6e9",
  measurementId: "G-8SFXFMS8RW",
};

const app = initializeApp(firebaseConfig);
const data = getDatabase(app);

export default function Home() {
  const [temperature, setTemperature] = useState(0);
  const [birds, setBirds] = useState(0);
  const [foodWater, setFoodWater] = useState(0);

  useEffect(() => {
    onValue(ref(data, "/temperature"), (snapshot) => {
      setTemperature(snapshot.val());
    });
    onValue(ref(data, "/foodWater"), (snapshot) => {
      setFoodWater(snapshot.val());
    });
    onValue(ref(data, "/birds"), (snapshot) => {
      setBirds(snapshot.val());
    });
  }, []);

  const handleTemperatureChange = (event) => {
    set(ref(data, "/temperature"), parseInt(event.target.value));
  }
  
  const handleBirdsChange = (newBirds) => {
    set(ref(data, "/birds"), newBirds);
  }
  
  const handleFoodWaterChange = (event) => {
    set(ref(data, "/foodWater"), parseInt(event.target.value));
  }
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Granja Sifu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={styles.title}>
        Remote Aviary Controller
      </h1>
      <Container>
        <Row>
          <Col>
            <FoodWater foodWater={foodWater} manageFW={handleFoodWaterChange}/>
          </Col>
          <Col>
            <Temperature temp={temperature} manageTemp={handleTemperatureChange}/>
          </Col>
          <Col>
            <Birds birds={birds} manageBirds={handleBirdsChange}/>
          </Col>
        </Row>
      </Container>
    </div>
  );
}

// get(child(dbRef, `/`))
//   .then((snapshot) => {
//     if (snapshot.exists()) {
//       setValues(snapshot.val());
//     } else console.log("No data available");
//   })
//   .catch((error) => console.error(error));