import Head from "next/head";
import { useState, useEffect } from "react";
import { initializeApp } from "firebase/app";
import { getDatabase, ref, child, get, onValue } from "firebase/database";
import uniqid from "uniqid";

import Block from "../src/components/Block";
import styles from "../styles/Home.module.css";
import Temperature from "../src/components/Temperature";

const firebaseConfig = {
  apiKey: "AIzaSyCS2xpG7sXRq6QzVzPT_uj3CRwj8b-N-JU",
  authDomain: "aviaryiot-se.firebaseapp.com",
  databaseURL: "https://aviaryiot-se-default-rtdb.firebaseio.com",
  projectId: "aviaryiot-se",
  storageBucket: "aviaryiot-se.appspot.com",
  messagingSenderId: "73299433036",
  appId: "1:73299433036:web:6dafb44d4597408822c6e9",
  measurementId: "G-8SFXFMS8RW",
};

const app = initializeApp(firebaseConfig);
const data = getDatabase(app);

export default function Home() {
  const [values, setValues] = useState({});
  const [temperature, setTemperature] = useState(0);

  useEffect(() => {
    onValue(ref(data, "/temperature"), (snapshot) => {
      setTemperature(snapshot.val());
    });
  }, []);
  
  return (
    <div className={styles.container}>
      <Head>
        <title>An Incredible Name</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          An Incredible <a href="https://github.com/JoMaAlves">Name!</a>
        </h1>

        <h1>{temperature}°C</h1>

        <Temperature temp={temperature}/>
      </main>
    </div>
  );
}

// get(child(dbRef, `/`))
//   .then((snapshot) => {
//     if (snapshot.exists()) {
//       setValues(snapshot.val());
//     } else console.log("No data available");
//   })
//   .catch((error) => console.error(error));